kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: namespace
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/created-by: kubectl
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/usage: argocd-namespace